### ISSUE TITLE
Google Now music commands incorrectly followed

### ISSUE THREAD

**Issue by krimin-killr21** [kabouzeid/phonograph-issue-tracker#25] opened 2015-09-11 04:27 UTC
Giving a command in Google Now to play a song song always causes the first alphabetical song by that artist to play, instead of specifically the requested song.

**Comment by kabouzeid** [comment] 2015-09-11 10:47
Thats Google Nows fault.

**Comment by uudruid74** [comment] 2015-10-02 01:46
This seems to work fine with Google Play.  How is this?

**Comment by Moter8** [comment] 2015-10-03 12:27
I'm facing this issue too! I tried this with some albums/artists and I saw a pattern.

"Spiele Baba aller Babas ab" --> opens Phonograph and puts 2 tracks of "415" in the playlist and then some tracks of "Baba aller Babas", then of "415" again and so on. Both of these albums are of the same artist. Same command works fine using the Play Music app.

"Spiele Asphalt Massaka 3 ab" --> opens Phonograph and plays a track of the artist's album, then of another one, then one track of the correct one...

**Comment by Moter8** [comment] 2015-10-03 12:47
[Video showcasing the issue](https://drive.google.com/file/d/0BzRp-cLiZDUJOGFjcEtRZDRMRVk/view?usp=sharing).

Phonograph seems to just pick the Album's artist and then play all of that artist's tracks in alphabetical order.

**Comment by uudruid74** [comment] 2015-10-06 17:34
I suppose its time to fork this since its a WONTFIX.

**Comment by kabouzeid** [comment] 2015-10-09 13:12
@uudruid74 Phonograph is on a private GitHub repo. The link is only a placeholder for future projects yet... Also I can't reproduce the bug above. For me it works perfectly fine on several devices!

**Closed by kabouzeid** 2015-10-09 13:12 UTC
Labels: wontfix
