### ISSUE TITLE
Very noticeable delay in playing songs on the OnePlus One running Lollipop.

### ISSUE THREAD

**Issue by tarun-verma** [kabouzeid/phonograph-issue-tracker#27] opened 2015-09-11 14:19 UTC
When I tap on any song I want to play on my OnePlus One device, there's a noticeable (> 5 seconds) delay till the song actually starts playing. I haven't noticed this issue on my Nexus 5.

Both of these devices are running CM 12.1 snapshot builds (which are supposed to be more stable than the nightlies). I have also tried other ROMs on my OnePlus One device (even the buggy as hell stock one), to no avail. Also, the issue is still persistent if I enable gapless playback in the app's settings. All it does is just remove the delay time when songs are being played in succession (when I'm playing an album, for example).

**Comment by kabouzeid** [comment] 2015-09-11 18:02
Duplicate of issue #2

**Closed by kabouzeid** 2015-09-11 18:02 UTC
Labels: duplicate
